"""The shared state of one UAE demo-dataset build.

The generator is split so that several people (or agents) can work on it at
once without editing each other's code:

* ``tools/uae_demo/reference.py`` builds the reference tables (activity codes,
  drugs, bundling edits, policies …);
* ``tools/uae_demo/base.py`` builds a clean, plausible population — providers,
  clinicians, members, cover, claims with lines, payments — and registers the
  claim factory below;
* ``tools/uae_demo/inject_<family>.py`` (one per scenario family: ent, pay, cln,
  phr, doc, net, pol, anl) each plant the patterns their controls look for,
  and record what they planted in the ANSWER KEY (``World.record``);
* ``tools/make_uae_demo_dataset.py`` runs them in a fixed order and writes the
  tables, the zip, the held-out evaluation labels and the answer key.

Everything is seeded from one ``numpy.random.Generator`` so the whole build
reproduces exactly.

THE ANSWER KEY IS NEVER READ BY DETECTION CODE. It is written beside the
dataset (``data/uae_demo.strata.csv``), not inside it, and
``tools/verify_uae_demo_dataset.py`` plus a governance test assert that no
module under ``src/`` refers to it.

An injector's contract::

    def inject(world: World) -> None:
        # choose claims/members/providers that no other injector has used,
        # modify them or add rows so the pattern exists in the data,
        # then say what was planted:
        world.record("PAY-02 unbundling", rule_ids=["PAY-02-R01"], claim_ids=[...])

Rules for injectors:

1. Take claims with :meth:`World.take_claims` (it never hands the same claim to
   two injectors) or create new ones with :meth:`World.make_claim`.
2. Keep every table internally consistent: if you change a line amount,
   change the header gross; if you add a claim, add its lines, diagnosis,
   encounter and remittance (``make_claim`` does all of that).
3. Plant each pattern at a modest volume (typically 0.1–1% of claims, or a
   handful of entities) — enough for the control to fire, far too few to
   dominate the queue or trip the alert-volume ceiling.
4. Record every planted item with the rule ids it is meant to exercise.
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass, field
from typing import Any, Callable, Iterable, Sequence

import numpy as np
import pandas as pd

__all__ = ["World", "SEED", "PERIOD_START", "PERIOD_END", "SYNTHETIC_NOTICE"]

SEED = 20260927
#: Eighteen months. The FX table is irrelevant here (every amount is AED), so
#: the only constraint on the period is enough history for the change-point
#: detectors (six months minimum) and a temporal split that leaves both models
#: a healthy training and scoring set.
PERIOD_START = _dt.date(2024, 7, 1)
PERIOD_END = _dt.date(2025, 12, 31)

SYNTHETIC_NOTICE = (
    "SYNTHETIC. Generated by tools/make_uae_demo_dataset.py to exercise the engine. "
    "No row describes a real person, provider, payer or claim. A check that passes on "
    "data built to pass it is a test of the check, not evidence that it detects fraud."
)


@dataclass
class World:
    rng: np.random.Generator
    start: _dt.date = PERIOD_START
    end: _dt.date = PERIOD_END
    tables: dict[str, pd.DataFrame] = field(default_factory=dict)
    #: The answer key: one row per planted item. Never read by detection code.
    strata: list[dict[str, Any]] = field(default_factory=list)
    #: Claims already used by an injector (or reserved by the base build).
    used_claims: set[str] = field(default_factory=set)
    #: Entities (providers, members, agents, clinicians…) already used by an injector.
    used_entities: set[str] = field(default_factory=set)
    #: Held-out evaluation label per claim (1 = planted issue). Evaluation only.
    positive_claims: set[str] = field(default_factory=set)
    _counters: dict[str, int] = field(default_factory=dict)
    #: Set by base.py: builds one complete claim across every claim table.
    claim_factory: Callable[..., str] | None = None
    notes: list[str] = field(default_factory=list)
    #: Build-time lookups shared between modules (set by reference.py/base.py:
    #: code catalogue, clinician index, tariff lookup …). Not written out.
    context: dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------ identities

    def new_id(self, prefix: str, width: int = 7) -> str:
        n = self._counters.get(prefix, 0) + 1
        self._counters[prefix] = n
        return f"{prefix}{n:0{width}d}"

    def seed_counter(self, prefix: str, value: int) -> None:
        self._counters[prefix] = max(self._counters.get(prefix, 0), int(value))

    # ---------------------------------------------------------------- tables

    def table(self, name: str) -> pd.DataFrame:
        return self.tables.get(name, pd.DataFrame())

    def append(self, name: str, rows: Iterable[dict[str, Any]] | pd.DataFrame) -> None:
        frame = rows if isinstance(rows, pd.DataFrame) else pd.DataFrame(list(rows))
        if frame.empty:
            return
        current = self.tables.get(name)
        self.tables[name] = frame if current is None or current.empty else pd.concat(
            [current, frame], ignore_index=True)

    def ensure_column(self, name: str, column: str, default: Any = None) -> None:
        """Add a column to a table (filled with ``default``) if it is not there yet."""
        frame = self.tables.get(name)
        if frame is not None and column not in frame.columns:
            frame[column] = default

    def set_values(self, name: str, mask, **values: Any) -> None:
        frame = self.tables[name]
        mask = pd.Series(mask, index=frame.index) if not isinstance(mask, pd.Series) else mask
        target = frame.index[mask.reindex(frame.index, fill_value=False).astype(bool)]
        for column, value in values.items():
            if column not in frame.columns:
                frame[column] = None
            # pandas 3 refuses a bare array assigned through .loc when lengths or
            # dtypes do not line up exactly; an index-aligned Series is explicit.
            if isinstance(value, (list, tuple, np.ndarray, pd.Series)) and not isinstance(value, str):
                series = value if isinstance(value, pd.Series) else pd.Series(list(value), index=target)
                new = series.reindex(target)
            else:
                new = pd.Series([value] * len(target), index=target, dtype=object)
            col = frame[column]
            if pd.api.types.is_numeric_dtype(col) and not pd.api.types.is_numeric_dtype(
                    pd.to_numeric(new, errors="coerce").dropna() if new.notna().any() else new):
                frame[column] = col.astype(object)
            try:
                frame.loc[target, column] = new.values
            except (TypeError, ValueError):
                frame[column] = frame[column].astype(object)
                frame.loc[target, column] = new.values

    # ---------------------------------------------------------------- claims

    def take_claims(
        self,
        n: int,
        where: Callable[[pd.DataFrame], pd.Series] | None = None,
        *,
        claim_type: str | Sequence[str] | None = None,
    ) -> pd.DataFrame:
        """Up to ``n`` random claim_header rows no injector has used yet; marks them used."""
        header = self.tables["claim_header"]
        mask = ~header["claim_sk"].isin(self.used_claims)
        if claim_type is not None:
            types = [claim_type] if isinstance(claim_type, str) else list(claim_type)
            mask &= header["claim_type"].isin(types)
        if where is not None:
            mask &= where(header).fillna(False).astype(bool)
        pool = header[mask]
        if pool.empty:
            return pool
        chosen = pool.sample(n=min(n, len(pool)), random_state=int(self.rng.integers(1 << 31)))
        self.used_claims.update(chosen["claim_sk"])
        return chosen

    def take_entities(self, table: str, key: str, n: int,
                      where: Callable[[pd.DataFrame], pd.Series] | None = None) -> pd.DataFrame:
        """Up to ``n`` rows of an entity table whose ``key`` no injector has used; marks them used."""
        frame = self.tables[table]
        mask = ~frame[key].astype(str).isin(self.used_entities)
        if where is not None:
            mask &= where(frame).fillna(False).astype(bool)
        pool = frame[mask]
        if pool.empty:
            return pool
        chosen = pool.sample(n=min(n, len(pool)), random_state=int(self.rng.integers(1 << 31)))
        self.used_entities.update(chosen[key].astype(str))
        return chosen

    def make_claim(self, **kwargs: Any) -> str:
        """Create one complete claim (header, lines, diagnoses, encounter, payment).

        Implemented by ``base.py``; see ``base.make_claim`` for the arguments.
        Returns the new ``claim_sk``, already marked used.
        """
        if self.claim_factory is None:
            raise RuntimeError("base.build() has not registered the claim factory yet.")
        claim_sk = self.claim_factory(self, **kwargs)
        self.used_claims.add(claim_sk)
        return claim_sk

    def lines_of(self, claim_ids: Iterable[str]) -> pd.DataFrame:
        lines = self.tables["claim_line"]
        return lines[lines["claim_sk"].isin(set(claim_ids))]

    def recompute_header_amounts(self, claim_ids: Iterable[str]) -> None:
        """Re-sum gross/net/patient share on the headers from their lines."""
        ids = set(claim_ids)
        lines = self.tables["claim_line"]
        # An injector that appended rows with a missing money value can leave
        # a column as object dtype; summing that raises. Coerce once here.
        for col in ("gross_amount", "net_amount", "patient_share"):
            if col in lines.columns and not pd.api.types.is_numeric_dtype(lines[col]):
                lines[col] = pd.to_numeric(lines[col], errors="coerce").fillna(0.0)
        sub = lines[lines["claim_sk"].isin(ids)]
        sums = sub.groupby("claim_sk")[["gross_amount", "net_amount", "patient_share"]].sum()
        header = self.tables["claim_header"]
        m = header["claim_sk"].isin(sums.index)
        idx = header.loc[m, "claim_sk"]
        for col in ("gross_amount", "net_amount", "patient_share"):
            header.loc[m, col] = idx.map(sums[col]).round(2).values

    # ------------------------------------------------------------ answer key

    def record(
        self,
        stratum: str,
        *,
        rule_ids: Sequence[str],
        claim_ids: Iterable[str] = (),
        subject_type: str = "claim",
        subject_ids: Iterable[str] = (),
        positive: bool = True,
        note: str = "",
    ) -> None:
        """Write planted items to the answer key (and the held-out labels)."""
        claim_ids = [str(c) for c in claim_ids]
        subject_ids = [str(s) for s in subject_ids]
        family = stratum.split("-")[0].split()[0] if stratum else ""
        for claim in claim_ids or [""]:
            self.strata.append({
                "stratum": stratum, "family": family, "rule_ids": ";".join(rule_ids),
                "claim_sk": claim, "subject_type": subject_type,
                "subject_ids": ";".join(subject_ids), "note": note,
            })
        if positive:
            self.positive_claims.update(c for c in claim_ids if c)

    # ------------------------------------------------------------------ util

    def random_date(self, start: _dt.date | None = None, end: _dt.date | None = None) -> _dt.date:
        start = start or self.start
        end = end or self.end
        span = max((end - start).days, 0)
        return start + _dt.timedelta(days=int(self.rng.integers(0, span + 1)))
