"""Validation Report — a one-screen plain summary, then the §11.2 artefacts in full.

The summary at the top is computed from the run every other page is showing,
not read out of the report files, so it cannot disagree with the rest of the
app. It says, in words: which file, how many claims, how many checks ran fully,
in a simplified form or not at all, how many cases and what they suggest, the
money involved split into established and not-yet-established (never added),
the models' status, and what cannot be measured yet and why. Nothing in it is a
number the engine did not measure.

The full technical report and every downloadable artefact sit on the later
tabs, unchanged, and can be regenerated from the current run.
"""

from __future__ import annotations

import html
import re

import pandas as pd
import streamlit as st

from common import (
    ROOT, banner, dataframe, empty_state, friendly_failure, headline_cards, note, page_header,
    pipeline, require_page, session_banner, status_chip, synthetic_banner,
)
from components.data_help import (
    adapter_labels, coverage, dataset_info, disposition_sentence, exposure_split,
    model_sentences, money, plural, unmeasurable, words,
)
from dataset import active_dataset
from fwa.auth import Permission
from fwa.presentation import standard_text

REPORTS = ROOT / "reports"

MARKDOWN_ARTEFACTS = {
    "Validation report": "validation_report.md",
    "Release-gate report": "release_gate_report.md",
    "Model card": "model_card.md",
    "Limitations": "limitations.md",
}

CSV_ARTEFACTS = {
    "Control coverage matrix (all 164 controls)": "control_coverage_matrix.csv",
    "Traceability matrix (Appendix D, regenerated from code)": "traceability_matrix.csv",
    "Operational metrics": "metrics.csv",
    "Evaluation protocol": "evaluation_protocol.csv",
    "Precision by ground-truth source": "precision_by_ground_truth_source.csv",
    "Recall by fraud type": "recall_by_fraud_type.csv",
    "Parameter registry": "parameter_registry.csv",
    "Canonical population report": "canonical_population_report.csv",
    "Control run report": "control_run_report.csv",
    "Case queue": "case_queue.csv",
}

_SOURCE = re.compile(r"Source `([^`]+)`")


def _run_gate_if_needed(result) -> None:
    """The same checklist run the Pattern-finding models page does, so the summary can say it."""
    layer = getattr(result, "models", None)
    anomaly = getattr(layer, "anomaly", None) if layer is not None else None
    if anomaly is None or not getattr(anomaly, "models", None) or layer.gate_verdicts:
        return
    from fwa.evaluation import MetricSuite

    config = result.config
    capacity = max(int(config.get("alerts_per_reviewer_per_day"))
                   * int(config.get("reviewer_count")), 1)
    layer.run_gate(outcomes=MetricSuite(result).provider_outcomes(), capacity=capacity)


def _report_source() -> str:
    path = REPORTS / "validation_report.md"
    try:
        head = path.read_text(encoding="utf-8")[:2000]
    except Exception:
        return ""
    m = _SOURCE.search(head)
    return m.group(1) if m else ""


# ---------------------------------------------------------------------------
# the plain summary
# ---------------------------------------------------------------------------


def _summary(result) -> None:
    spec = active_dataset()
    info = dataset_info(spec)
    cov = coverage(result)
    claims = len(result.claims)
    cases = len(result.cases.cases)
    flags = len(result.signals)
    established, not_established, n_est, n_not = exposure_split(result)
    adapter = adapter_labels().get(spec.adapter, spec.adapter)

    st.markdown("## Summary in plain English")
    headline_cards([
        (f"{claims:,}", "claims in the file this report describes."),
        (f"{cov.full + cov.simplified:,} of {cov.total:,}",
         f"checks could run ({cov.full:,} fully, {cov.simplified:,} in a simplified form)."),
        (f"{cases:,}", "cases for review. Each is a reason to look, not proof of fraud."),
        (money(established), f"established across {plural(n_est, 'case')}: a clear rule failed."),
        (money(not_established), f"not yet established, across {plural(n_not, 'case')}. "
                                 "Shown separately and never added to the figure before."),
    ])

    synthetic = " It is SYNTHETIC: generated by a program to exercise the engine." \
        if info.get("synthetic") else ""
    lines = [
        f"**What was run.** Every check and model ran over **{html.escape(str(info['name']))}** "
        f"({html.escape(spec.name)}, {claims:,} claims, read as {html.escape(adapter)}).{synthetic}",
        f"**Which checks could run.** {cov.headline()}",
        f"**What it found.** {flags:,} flags, grouped into {cases:,} cases for review. "
        + (f"Of the cases, {disposition_sentence(result)} " if cases else "")
        + html.escape(standard_text("not_proof")) + " "
        + html.escape(standard_text("priority_not_decision")),
        f"**Money involved.** {money(established)} is established, because a clear rule failed. "
        f"Separately, {money(not_established)} is not yet established: it is the full value of "
        "claims that look unusual. The two are never added together. "
        + html.escape(standard_text("not_savings")),
    ]
    for line in lines:
        st.markdown(line)

    st.markdown("**The pattern-finding models.**")
    with friendly_failure("the models' status"):
        _run_gate_if_needed(result)
    for sentence in model_sentences(result):
        st.markdown(f"- {sentence}")

    gaps = unmeasurable(result)
    if gaps:
        by_reason: dict[str, list[str]] = {}
        for name, why in gaps:
            by_reason.setdefault(why, []).append(name)
        bullets = "\n".join(f"- {', '.join(names)}: because {why}."
                            for why, names in by_reason.items())
        st.markdown(
            "**What cannot be measured yet.** The engine shows these as 'can't be measured yet' "
            "rather than inventing a number. How often a flag turns out to be a real problem "
            "needs reviewers' decisions, and none has been recorded on this run.\n\n" + bullets)
    else:
        st.markdown("**What cannot be measured yet.** How often a flag turns out to be a real "
                    "problem needs reviewers' decisions, and none has been recorded on this run, "
                    "so it is not reported as a number.")

    closing = standard_text("shadow")
    if info.get("synthetic"):
        closing += (" A check or model that passes on data built to pass it is a test of the "
                    "check, not evidence that it detects fraud.")
    note(closing)


# ---------------------------------------------------------------------------
# the technical report and files
# ---------------------------------------------------------------------------


def _report_files_stale(result) -> str:
    source = _report_source()
    current = str(getattr(result, "source_name", "") or active_dataset().name)
    if source and current and source != current:
        return (f"The report files below were generated from {source}, not from {current}, the "
                "file in use now. The summary above describes the file in use; regenerate the "
                "reports to bring the files in line.")
    return ""


def _regenerate(result, state, *, label: str, primary: bool = False) -> None:
    if not state.can(Permission.RUN_PIPELINE):
        st.caption("Your role cannot regenerate the reports. An analyst or administrator can.")
        return
    if st.button(label, type="primary" if primary else "secondary", key=f"regen_{primary}",
                 help="Rewrites every report file from the run the app is showing now. Use it "
                      "after loading a different file, so the files match the summary. It takes "
                      "about a minute."):
        from fwa.evaluation import ReportBuilder

        with friendly_failure("the report regeneration",
                              "Try again. If it keeps failing, ask an administrator to check the "
                              "application log and that the reports folder can be written to."):
            with st.spinner("Regenerating every report file…"):
                written = ReportBuilder(result, REPORTS).build_all()
            st.success(f"Regenerated {len(written)} report files from the file in use.")


def _technical(result, state) -> None:
    st.markdown("## Full technical report")
    stale = _report_files_stale(result)
    if stale:
        st.warning(stale)
    path = REPORTS / "validation_report.md"
    if not path.exists():
        empty_state("No report has been generated yet",
                    "Press the button below, or run "
                    "`python -m fwa.run_validation` from the project folder. The run is "
                    "deterministic: fixed seed, recorded fingerprint.")
        _regenerate(result, state, label="Generate the reports now", primary=True)
        return
    chosen = st.selectbox(
        "Report", list(MARKDOWN_ARTEFACTS), key="vr_markdown",
        help="What it does: picks which written report to read. When to change it: the "
             "validation report is the main one; the model card covers the pattern-finding "
             "models, and 'Limitations' lists everything the run cannot show.",
    )
    target = REPORTS / MARKDOWN_ARTEFACTS[chosen]
    if not target.exists():
        empty_state("Not generated", f"{target.name} was not produced by the last run. "
                                     "Regenerate the reports to create it.")
    else:
        text = target.read_text(encoding="utf-8")
        st.caption(words("artefacts").get(target.name, ""))
        st.download_button(f"Download {target.name}", text, file_name=target.name,
                           mime="text/markdown", key="vr_md_download",
                           help="Saves this report as a text file with simple formatting.")
        st.markdown("---")
        st.markdown(text)
    st.markdown("---")
    _regenerate(result, state, label="Regenerate all reports from the current run")


def _files(result, state) -> None:
    st.markdown("## Supporting files")
    st.caption("Every table behind the reports, as a spreadsheet file. Each number in them is a "
               "measured output of this run, a threshold labelled as such, or marked as not "
               "measurable on this file.")
    if not REPORTS.exists():
        empty_state("No report files yet", "Generate the reports on the previous tab first.")
        return
    stale = _report_files_stale(result)
    if stale:
        st.warning(stale)
    chosen = st.selectbox(
        "File", list(CSV_ARTEFACTS), key="vr_csv",
        help="What it does: picks which supporting table to preview and download. When to "
             "change it: the control coverage matrix lists all 164 checks; the metrics file "
             "lists every measure, including the ones that cannot be measured yet.",
    )
    path = REPORTS / CSV_ARTEFACTS[chosen]
    if not path.exists():
        empty_state("Not generated", f"{path.name} was not produced by the last run. "
                                     "Regenerate the reports to create it.")
        return
    st.caption(words("artefacts").get(path.name, ""))
    with friendly_failure(f"the file {path.name}", "Regenerate the reports and try again."):
        frame = pd.read_csv(path)
        st.download_button(f"Download {path.name}", path.read_bytes(), file_name=path.name,
                           mime="text/csv", key="vr_csv_download",
                           help="Saves this table for a spreadsheet.")
        if "status" in frame.columns:
            counts = frame["status"].value_counts()
            st.markdown(" ".join(status_chip(str(k)) + f" {v}" for k, v in counts.items()),
                        unsafe_allow_html=True)
        dataframe(frame, height=520)
    with st.expander("Technical details: run identity", expanded=False):
        dataframe(pd.DataFrame([
            {"item": "Seed (cfg.random_seed)", "value": str(result.seed)},
            {"item": "Parameter fingerprint (stamped onto every signal)",
             "value": result.config.fingerprint()},
            {"item": "Files in reports/", "value": str(len(list(REPORTS.glob("*"))))},
        ]))


# ---------------------------------------------------------------------------
# page
# ---------------------------------------------------------------------------


def render() -> None:
    state = require_page("Validation Report", Permission.VIEW_VALIDATION_REPORT)
    session_banner(state)
    page_header("Validation Report")
    banner()
    synthetic_banner()

    result = pipeline()

    tab_summary, tab_report, tab_files = st.tabs(
        ["Summary", "Full technical report", "Supporting files"])
    with tab_summary:
        with friendly_failure("the plain summary"):
            _summary(result)
    with tab_report:
        with friendly_failure("the technical report"):
            _technical(result, state)
    with tab_files:
        with friendly_failure("the supporting files"):
            _files(result, state)
