"""Synthetic discharge summaries — clearly and permanently marked (build brief §8).

    "The CSV has no documents, so state that plainly and build the pipeline
     against **clearly-labelled synthetic notes**: generate discharge summaries
     per claim (bilingual English/Arabic where feasible) that are *consistent*
     with the claim for most rows and *deliberately inconsistent* for an
     injected subset, writing them to ``data/synthetic_documents/`` with a
     ``SYNTHETIC`` marker in every filename and in the file body."

Three rules this generator follows without exception:

1. **Every file is marked.** ``SYNTHETIC`` appears in the filename, in the first
   line of the body, in the footer, and in a machine-readable header field. A
   document that loses its marker has to be treated as real, and the cheapest
   way to guarantee that never happens is to make the marker structural.
2. **The inconsistent subset is recorded.** ``manifest.csv`` lists which claims
   received an injected inconsistency and what was injected, so a reader of the
   validation report can tell a detection from a coincidence. This is the
   "synthetic-corruption injection, permanently marked synthetic" of §6.6.
3. **Nothing generated here is ever presented as a clinical fact.** The
   documents exist to exercise the §4.9 pipeline — classification, OCR hook,
   language detection, extraction, structured comparison, span-grounded
   evidence rendering. They are not evidence about anyone.

Arabic is included because §4.9 requires extraction quality to be reported
**separately by language**, and a pipeline evaluated on one language cannot make
that claim. The Arabic text here is template-generated and simple; the honest
consequence is that Arabic extraction quality on this corpus says something
about the pipeline's plumbing and nothing about its performance on real Arabic
clinical documentation, and the report states exactly that.
"""

from __future__ import annotations

import datetime as _dt
import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd

__all__ = ["SyntheticDocument", "SyntheticCorpus", "SYNTHETIC_MARKER", "render_discharge_summary"]

SYNTHETIC_MARKER = "SYNTHETIC"

_HEADER_EN = """*** {marker} DOCUMENT — GENERATED BY THE UAE-FWA-ENGINE ARTEFACT ***
*** NOT A REAL CLINICAL RECORD. NOT ABOUT A REAL PERSON. GENERATED {generated} ***

DISCHARGE SUMMARY ({marker})
Facility reference: {provider}
Patient reference: {member}
Claim reference: {claim}
Admission date: {admit}
Discharge date: {discharge}
Length of stay: {los} day(s)
Primary diagnosis: {dx_code} — {dx_text}
"""

_BODY_EN = """
CLINICAL COURSE
The patient was admitted on {admit} with presentation consistent with {dx_text}.
The recorded inpatient stay was {los_text} day(s). Management during admission
followed the standard pathway for {dx_text}; no intercurrent complication was
documented. {extra}

MEDICATION AND SUPPLIES
Pharmacy charges represented approximately {pharm} of the total billed amount for
this admission.

DISPOSITION
The patient was discharged on {discharge} in a stable condition with routine
follow-up arranged.
"""

_FOOTER_EN = """
--- END OF {marker} DOCUMENT ---
This file was generated for software testing. Every fact in it is invented.
"""

_HEADER_AR = """*** وثيقة {marker} — تم إنشاؤها بواسطة أداة UAE-FWA-ENGINE ***
*** ليست سجلاً سريرياً حقيقياً. لا تخص شخصاً حقيقياً. ***

ملخص الخروج ({marker})
المرجع المنشأة: {provider}
مرجع المريض: {member}
مرجع المطالبة: {claim}
تاريخ الدخول: {admit}
تاريخ الخروج: {discharge}
مدة الإقامة: {los} يوم
التشخيص الأساسي: {dx_code} — {dx_text}
"""

_BODY_AR = """
المسار السريري
تم إدخال المريض بتاريخ {admit} بأعراض تتوافق مع {dx_text}.
بلغت مدة الإقامة المسجلة {los_text} يوم. تمت المعالجة وفق المسار المعتاد
ولم يتم توثيق أي مضاعفات. {extra}

الأدوية والمستلزمات
شكلت مصاريف الصيدلية حوالي {pharm} من إجمالي المبلغ المطالب به.

الخروج
تم خروج المريض بتاريخ {discharge} بحالة مستقرة مع متابعة روتينية.
"""

_FOOTER_AR = """
--- نهاية وثيقة {marker} ---
تم إنشاء هذا الملف لأغراض اختبار البرمجيات. جميع الحقائق الواردة فيه مُختلقة.
"""

_EXTRA_PHRASES = [
    "A routine review was documented on each day of the admission.",
    "Vital signs remained within expected limits throughout.",
    "The treating team documented daily progress notes.",
    "No transfer to a higher level of care was required.",
    "Discharge planning commenced on the second day of admission.",
]

#: The injectable inconsistency types. Each is a *structured* conflict between
#: the note and the claim, because a structured conflict is what DOC-01-R02 is
#: defined to detect. A vague inconsistency would test nothing.
INCONSISTENCY_TYPES = (
    "stay_length_conflict",       # the note states a different length of stay
    "diagnosis_conflict",         # the note describes a different condition
    "date_conflict",              # the note states a different admission date
)


def render_discharge_summary(fields: dict[str, Any], language: str = "en", addendum: str = "") -> str:
    """Render one discharge summary from the same templates the corpus uses.

    Used by the SYNTHETIC multi-table demo generator (``tools/uae_demo``) so that
    the documents shipped inside that dataset and the ones this module writes
    share one structure — and one ``SYNTHETIC`` marker. ``fields`` needs the
    template keys (provider, member, claim, admit, discharge, los, los_text,
    dx_code, dx_text, pharm, extra); ``marker`` and ``generated`` default to the
    marker and a fixed label so output is reproducible. ``addendum`` is inserted
    before the footer.
    """
    values = {"marker": SYNTHETIC_MARKER, "generated": "by a seeded generator", **fields}
    if language == "ar":
        head, body, foot = _HEADER_AR, _BODY_AR, _FOOTER_AR
    else:
        head, body, foot = _HEADER_EN, _BODY_EN, _FOOTER_EN
    text = (head + body).format(**values)
    if addendum:
        text += "\n" + addendum.rstrip() + "\n"
    return text + foot.format(**values)


@dataclass
class SyntheticDocument:
    claim_sk: str
    filename: str
    language: str
    text: str
    ocr_confidence: float
    is_inconsistent: bool
    injected_inconsistency: str
    stated_los: int | None
    stated_diagnosis: str | None
    stated_admission: str | None

    def to_row(self) -> dict[str, Any]:
        return {
            "claim_sk": self.claim_sk,
            "filename": self.filename,
            "language": self.language,
            "ocr_confidence": round(self.ocr_confidence, 3),
            "is_inconsistent": self.is_inconsistent,
            "injected_inconsistency": self.injected_inconsistency,
            "stated_los": self.stated_los,
            "stated_diagnosis": self.stated_diagnosis,
            "stated_admission": self.stated_admission,
            "synthetic": True,
        }


class SyntheticCorpus:
    """Generates and holds the corpus, plus its manifest."""

    def __init__(self, config, output_dir: Path | str | None = None) -> None:
        self.config = config
        self.seed = int(config.get("random_seed"))
        self.inconsistency_rate = float(config.get("nlp_synthetic_inconsistency_rate"))
        self.output_dir = Path(output_dir) if output_dir else Path("data/synthetic_documents")
        self.documents: dict[str, SyntheticDocument] = {}

    # ------------------------------------------------------------------ build

    def generate(
        self, claims: pd.DataFrame, n: int | None = None, write: bool = True
    ) -> dict[str, SyntheticDocument]:
        rng = random.Random(self.seed)
        sample = claims if n is None else claims.sample(min(n, len(claims)), random_state=self.seed)
        if write:
            self.output_dir.mkdir(parents=True, exist_ok=True)

        for row in sample.itertuples(index=False):
            arabic = rng.random() < 0.30
            inconsistent = rng.random() < self.inconsistency_rate
            injected = rng.choice(INCONSISTENCY_TYPES) if inconsistent else ""

            true_los = int(row.length_of_stay_days)
            true_dx = str(row.diagnosis_primary)
            true_dx_text = str(getattr(row, "diagnosis_description", "") or self._dx_text(claims, true_dx))
            admit = pd.Timestamp(row.service_date)
            discharge = pd.Timestamp(row.discharge_date)

            stated_los, stated_dx, stated_admit = true_los, true_dx_text, admit
            if injected == "stay_length_conflict":
                stated_los = max(1, true_los + rng.choice([-9, -7, 7, 9, 12]))
            elif injected == "diagnosis_conflict":
                stated_dx = self._other_dx_text(claims, true_dx, rng)
            elif injected == "date_conflict":
                stated_admit = admit + pd.Timedelta(days=rng.choice([-11, -6, 6, 11]))

            # OCR confidence: most documents are clean, a minority are poor.
            # §6.3 requires that NLP results "visibly degrade their confidence
            # when OCR quality is poor", so a poor-quality subset must exist.
            ocr = 0.95 if rng.random() > 0.18 else round(rng.uniform(0.40, 0.68), 2)

            fields = {
                "marker": SYNTHETIC_MARKER,
                "generated": _dt.date.today().isoformat(),
                "provider": row.provider_sk,
                "member": row.member_sk,
                "claim": row.claim_sk,
                "admit": stated_admit.date().isoformat(),
                "discharge": discharge.date().isoformat(),
                "los": stated_los,
                "los_text": stated_los,
                "dx_code": true_dx,
                "dx_text": stated_dx,
                "pharm": f"{float(row.pharmacy_bill_ratio):.0%}",
                "extra": rng.choice(_EXTRA_PHRASES),
            }
            if arabic:
                text = (_HEADER_AR + _BODY_AR + _FOOTER_AR).format(**fields)
                language = "ar"
            else:
                text = (_HEADER_EN + _BODY_EN + _FOOTER_EN).format(**fields)
                language = "en"

            filename = f"{SYNTHETIC_MARKER}_discharge_{row.claim_sk}_{language}.txt"
            doc = SyntheticDocument(
                claim_sk=str(row.claim_sk),
                filename=filename,
                language=language,
                text=text,
                ocr_confidence=ocr,
                is_inconsistent=inconsistent,
                injected_inconsistency=injected,
                stated_los=stated_los,
                stated_diagnosis=stated_dx,
                stated_admission=stated_admit.date().isoformat(),
            )
            self.documents[doc.claim_sk] = doc
            if write:
                (self.output_dir / filename).write_text(text, encoding="utf-8")

        if write:
            self.manifest().to_csv(self.output_dir / "manifest.csv", index=False)
            (self.output_dir / "README.txt").write_text(self._readme(), encoding="utf-8")
        return self.documents

    # ---------------------------------------------------------------- reports

    def manifest(self) -> pd.DataFrame:
        rows = [d.to_row() for d in self.documents.values()]
        return pd.DataFrame(rows) if rows else pd.DataFrame()

    def summary(self) -> dict[str, Any]:
        m = self.manifest()
        if m.empty:
            return {"documents": 0}
        return {
            "documents": len(m),
            "by_language": m["language"].value_counts().to_dict(),
            "inconsistent": int(m["is_inconsistent"].sum()),
            "inconsistency_types": m.loc[m["is_inconsistent"], "injected_inconsistency"]
            .value_counts().to_dict(),
            "poor_ocr": int((m["ocr_confidence"] < 0.7).sum()),
            "all_marked_synthetic": bool(m["synthetic"].all()),
        }

    def _readme(self) -> str:
        s = self.summary()
        return (
            f"{SYNTHETIC_MARKER} DOCUMENT CORPUS\n"
            f"{'=' * 60}\n\n"
            f"Every file in this directory is GENERATED. None of it is a real clinical record, "
            f"and none of it describes a real person, provider or event.\n\n"
            f"the claim extract contains no documents of any kind. This corpus exists so that the "
            f" document pipeline — classification, OCR hook, language detection, clinical "
            f"entity and negation extraction, structured comparison against the billed claim, "
            f"and span-grounded evidence rendering — can be exercised and demonstrated.\n\n"
            f"Documents: {s.get('documents', 0)}\n"
            f"By language: {s.get('by_language', {})}\n"
            f"Deliberately inconsistent: {s.get('inconsistent', 0)} "
            f"({s.get('inconsistency_types', {})})\n"
            f"Poor OCR quality: {s.get('poor_ocr', 0)} (so that confidence degradation is "
            f"observable,)\n\n"
            f"manifest.csv records exactly which claims received an injected inconsistency and "
            f"what was injected, so that a detection can be distinguished from a coincidence.\n\n"
            f"No figure derived from this corpus is a measurement of clinical-NLP performance. "
            f"It measures whether the pipeline's plumbing works.\n"
        )

    @staticmethod
    def _dx_text(claims: pd.DataFrame, code: str) -> str:
        if "diagnosis_description" in claims.columns:
            match = claims.loc[claims["diagnosis_primary"] == code, "diagnosis_description"]
            if not match.empty:
                return str(match.iloc[0])
        return code

    @staticmethod
    def _other_dx_text(claims: pd.DataFrame, code: str, rng: random.Random) -> str:
        if "diagnosis_description" in claims.columns:
            others = claims.loc[claims["diagnosis_primary"] != code, "diagnosis_description"].unique()
        else:
            others = claims.loc[claims["diagnosis_primary"] != code, "diagnosis_primary"].unique()
        return str(rng.choice(list(others))) if len(others) else "an unrelated condition"
